# Generated by Django 3.2.12 on 2022-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_choice', models.CharField(max_length=1000)),
                ('name_of_flower', models.CharField(max_length=1000)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower', models.URLField()),
                ('name_flower', models.CharField(max_length=1000)),
                ('color_choice', models.CharField(max_length=1000)),
            ],
        ),
    ]
