# Generated by Django 3.2.12 on 2022-03-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_choice_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flowers',
        ),
    ]
