# Generated by Django 3.2.12 on 2022-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='age',
            field=models.CharField(max_length=1000),
        ),
    ]
